server:
  port: 8083

logging.level.com.client.dao: debug

spring:
  application:
    name: Order
  datasource:
    name: order_database
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/demo1?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Dao.xml

eureka:
  client:
    healthcheck: #开启健康检查(依赖spring-boot-actuator)
      enabled: true #这个属性不会提示 修改健康检测方式为health监控
    service-url:
      defaultZone: http://eurekaserver01:6001/eureka/
  instance:
    hostname: server_order
    instance-id: server_order:8083
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10 # eureka client发送心跳给server端后，续约到期时间（默认90秒）
    lease-renewal-interval-in-seconds: 5 #发送心跳续约间隔

# 提供微服务的说明信息
info:
  appname: server_order