server:
  port: 9999
spring:
  application:
    name: Zuul

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver01:6001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1 # 每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-expiration-duration-in-seconds: 2 #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    prefer-ip-address: true # 以本机IP地址注册到eureka中，为默认为false则注册主机名
    hostname: springCloudZuul
    instance-id: springCloudZuul:9999 # 该服务的实例信息

zuul:
  ignoredServices: userhystrix # 过滤掉这种通过服务名称访问的方式，隐藏服务信息
  routes:
    user.serviceId: userhystrix
    user.path: /users/**

# 提供微服务的说明信息
info:
  appname: server_user_hystrix
