server:
  port: 6002

spring:
  application:
    name: eureka02

eureka:
  instance:
    hostname: eurekaserver02
  server:
    enable-self-preservation: false # 关闭自我保护，能随时剔除不可用的服务
    eviction-interval-timer-in-ms: 4000 # 剔除时间间隔，毫秒级
  client:
    register-with-eureka: false # 是否将自己注册到Eureka服务中，本身就是所有无需注册
    fetch-registry: false # 是否将自己注册到Eureka服务中，本身就是所有无需注册
    service-url:
      defaultZone: http://eurekaserver01:6001/eureka/,http://eurekaserver03:6003/eureka/
